### ISSUE TITLE
Error Parsing some wavs

### ISSUE THREAD

**Issue by nershman** [Zylann/audacity2reaper#3]
```
> python3 aup2rpp.py test/test2.aup
Overwriting  test/test2_wav_data/track0_clip0.wav
Converting blocks  [['test/test2_data/eff/d18/eff1833f.au', 'test/test2_data/eff/d1c/eff1c19a.au'], ['test/test2_data/eff/d18/eff184d4.au', 'test/test2_data/eff/d1c/eff1c90c.au']]
     {'magic': 779316836, 'data_offset': 6212, 'data_size': 4294967295, 'encoding': 6, 'sample_rate': 44100, 'channels': 1}
     {'magic': 779316836, 'data_offset': 6212, 'data_size': 4294967295, 'encoding': 6, 'sample_rate': 44100, 'channels': 1}
Traceback (most recent call last):
  File "aup2rpp.py", line 751, in <module>
    convert(args.audacity_project)
  File "aup2rpp.py", line 734, in convert
    convert_au_files_from_audacity_project(project, data_dir)
  File "aup2rpp.py", line 553, in convert_au_files_from_audacity_project
    samples_in_file = convert_au_files_to_wav(au_fpaths, dst_fpath)
  File "aup2rpp.py", line 290, in convert_au_files_to_wav
    w.append_multichannel_samples(samples_by_channel)
  File "aup2rpp.py", line 149, in append_multichannel_samples
    self.append_interleaved_samples(interleaved_sample_data)
  File "aup2rpp.py", line 163, in append_interleaved_samples
    f.write(struct.pack(sfc, v))
struct.error: short format requires (-32767 -1) <= number <= 32767
```

This seems to happen with specific samples in a track. If I delete them it processes normally.

**Comment by nershman** [comment]
The issue seems to  be when tracks are saved as 32-bit float, which allows dynamic range outside of the 16-bit PCM wav range.

It seems like WavWriter class accomodated 32-bit and low PCM but not 32 bit float, so that needs to be added.

**Comment by nershman** [comment]
Solved, the conversion to 16-bit had no cutoff. Please see my pull request https://github.com/Zylann/audacity2reaper/pull/4

it would be nice to support 32 bit float exports as well but that will be more time-consuming.
